services:
  - type: web
    name: square-catcher
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --pythonpath pycode app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
